# Generated by Django 4.2 on 2023-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
